### ISSUE TITLE
Browserside Debugging with console

### ISSUE THREAD

**Issue by cryptoquick** [chinedufn/percy#91]
I wasn't able to get this to work, but ideally, we'd have a mechanism for `console.log`-style browser debugging.

Also, as a Rust bonus, the extra code for logging should be able to be removed with a compiler directive, so while there is debugging code present for development, it is stripped from the build in production.

I checked out what was currently available, but I think we can do better, and simpler. They all seem to follow a similar formula:

- [`console_log`](https://github.com/iamcodemaker/console_log)
- [`wasm-logger`](https://gitlab.com/limira-rs/wasm-logger)
- [`wasm-bindgen-console-logger`](https://github.com/blm768/wasm-bindgen-console-logger)

I would prefer it if I could just add `info!("Message:", msg)` macros here and there, and they just automatically get stripped out for release builds. I'm not experienced with Rust enough to put this plan into action, though, so I suppose I'm seeking help and comments.

**Comment by chinedufn** [comment]
Ohhhh very interesting

Here's an example of a console.log macro.
 https://github.com/chinedufn/psd/blob/12deb5b1442e7b42cdcc3cf532e0f42b6a693636/examples/drag-drop-browser/src/lib.rs#L416-L424

Also I got notifications for your other issues / PR and I'll take a look after work!

You can usually manage dev vs. production by using `#[cfg(debug_assertions)]` so this should be totally possible.

Would

`cinfo!` `clog!` `cerror!` `cdebug!` and `cwarning!` make sense?

Then we could import them as `percy::cinfo` `percy::clog` etc

```sh
use percy::cinfo;

fn main () {
  // compiled away in production
  cinfo!("Hello world {}", 5);
}
```

**Comment by chinedufn** [comment]
Oh sorry I just looked at `console_log` and it looks like it does exactly what you're looking for.

You can do this to set the log level

```sh
// Development
#[cfg(debug_assertions)]
{
console_log::init_with_level(Level::Debug);
}

// Production
#[cfg(not(debug_assertions))]
{
console_log::init_with_level(Level::Error);
}
```

And then just make sure that the `console` feature for wasm-bindgen is in your Cargo.toml.

Would that work for you?

**Comment by cryptoquick** [comment]
Well, I ran into a couple pitfalls. Since, I'm building an isometric app, this can't be included in the app's Cargo.toml when I run the server.

Also, I couldn't figure out how to use (import) console_log's macros into my code.

**Comment by dbrgn** [comment]
In https://github.com/threema-ch/compose-area I'm using `console_log` and it works quite nicely. I haven't tried turning it off in a release build though.

**Comment by chinedufn** [comment]
> Well, I ran into a couple pitfalls. Since, I'm building an isometric app, this can't be included in the app's Cargo.toml when I run the server.

Hmm - what about if a `Cargo.toml` for an app crate [assuming the client, server, app pattern detailed in our isomorphic server example README](https://github.com/chinedufn/percy/blob/ba0c5baed643fcc712fbecbb797cff3fb57b4274/examples/isomorphic/README.md#app-crate) looked like this.

```toml
[features]
web-log = ["console_log"]
server-log = ["env_logger"]

[dependencies]
console_log = { version = "...", optional = true }
env_logger = { version = "...", optional = true }
```

So this way your server could build the app with the server-log feature and the client would use the web-log feature.

**Comment by limira** [comment]
My thoughts: as @chinedufn said above, but not limited to 'isomorphic app', this apply to any Rust app that has shared code between server and client (on browser). I have library crates that their `Cargo.toml` like:
```toml
[package]
name = "shared-lib"

[dependencies]
log = "0.4.6"
```
Note that these libs only depend on `log`, and in their code, you log by: `log::info!`, `log::error!`...

Then, both binary crates for server and client depend on `shared-lib`:
```toml
[package]
name = "server-app"

[dependencies]
shared-lib = { path = "..." }
log = "0.4.6"
your-favorite-crate-for-logging-on-server = "x.y.z"
```
and browser app:
```toml
[package]
name = "browser-app"

[dependencies]
shared-lib = { path = "..." }
log = "0.4.6"
your-favorite-crate-for-logging-on-browser = "x.y.z"
```
Is this OK?
